### ISSUE TITLE
Week Two Assignment

### ISSUE THREAD

**Issue by ellatronic** [ellatronic/portfolio#15]
Hello,

@DiyahM
@Keenahn
@LijieZhou

Completed week two assignment. Added columns to content div. Added contact page with form using formspring. 

So I've been working on my master branch while updating my portfolio, and I can add, commit, and push to the master branch just fine. But when I try to push to gh-pages, the terminal yells at me and says no. So I end up going on the github website and merging the master and gh-pages branches so the updates will show up on my portfolio webpage. Is there an easier way to do this from the terminal? I find when I switch to gh-pages in the terminal, it tells me to git pull, but when I do that, all the changes I just made on the master disappear on my computer and I've got all the old files back instead of the new ones I want to push.

**Comment by DiyahM** [comment]
Hi @ellatronic 

Great use of css and forms this week. Everything looks great. I did notice that you have a few <a> tags which link to sections within your page. For example: <a href="#about"></a>

However, on your page the 'about' section is a class. When linking to sections in the page specified using '#' this should correspond to an id on your page. Let me know if you have any further questions about this.

-Diyah

**Comment by keenahn** [comment]
Hi Ella, great job so far! Good use of HTML and CSS. Nice customization of the formspree form.

I can walk you through the process today for pushing to github pages. For now, use this command

$ git pull origin gh-pages
$ git checkout master
$ git merge master gh-pages
$ git checkout gh-pages
$ git merge gh-pages master
$ git push origin gh-pages

I can explain what each step is doing

**Comment by keenahn** [comment]
```
git checkout master       
# This switches to the master branch

git push origin master    
# This pushes your local master branch up to github

git pull origin           
# This pulls ALL branches from github and merges them with your local branches

git checkout gh-pages     
# This switches to your local gh-pages branch

git merge gh-pages origin/gh-pages 
# This makes sure that your local gh-pages is up to date with the branch you just pulled down from github

git merge master
# This brings your local gh-pages branch up to date with your local master branch

git push origin gh-pages
# This pushes your gh-pages branch up to github
```
