### ISSUE TITLE
Week one assignment complete

### ISSUE THREAD

**Issue by ellatronic** [ellatronic/portfolio#2]
@DiyahM
@Keenahn
@LijieZhou

Completed week one homework assignment. Time spent: approx. 4 hrs over 2 days.

**Comment by LijieZhou** [comment]
Hi @ellatronic Congratulations on finishing up our first assignment. You definitely achieved a lot in the past week. I like you put github on your site. This is a great way for people in the developers' world to know the cool projects you're doing. 

Something you may think more carefully about is whether table is a good choice for your site. What made you make this decision? What are the pros and cons? Read this article and think about it in your case. 

http://vanseodesign.com/css/css-divs-vs-tables/

Lijie

**Comment by DiyahM** [comment]
Hi @ellatronic - Just adding my two cents. In general, push to both your master branch and gh-pages branch. Locally, on your machine, make all updates on the master branch. You can switch between branches by doing 'git checkout <branch-name>'. Make updates on the master branch, and push updates to the master branch.

When you are ready for your changes to show up on your webpage, then push to gh-pages by doing a 'git push origin gh-pages'

**Comment by ellatronic** [comment]
Thanks for the feedback.

@LijieZhou I originally used tables since we went over tables in class. I read the article you posted though and have changed my layout to divs instead.

@DiyahM Okay, will do!
