### ISSUE TITLE
Week Three Assignment

### ISSUE THREAD

**Issue by ellatronic** [ellatronic/portfolio#25]
Hi all,
@DiyahM
@Keenahn
@LijieZhou

So, I picked two in-class assignments to customize and add as an image to the projects section of my portfolio. I've only added one so far though, I'm still working on customizing the second one and will add it when I'm finished but it will basically be the displayed on the portfolio in the same style and format as the assignment already on there. So, I haven't finished yet but I wanted to turn something in so you guys could look at it. 

Also, so far I've been making new .html's for new pages I want in my portfolio, but I was wondering if there was an easier/more efficient way to make every page have the navigation, footer, etc. besides putting the code for these on each .html since it's the same thing anyways. Like the only thing different in each page is what's inside the content div, the other stuff is all the same.

Total hours so far: 14

**Comment by DiyahM** [comment]
Love the portfolio and the customizations you've made for each project. You'll have a lot more to add once we get through javascript, ajax, and apis. This is a great start for showing potential employers. 

For partials and templates, you can look into mustachejs https://github.com/janl/mustache.js/ or handlebarsjs http://handlebarsjs.com/. Take a look at both, and if either interest you, we can put together an advanced topic. 

-Diyah
